/* This file was generated by SableCC (http://www.sablecc.org/). */

package syntax.node;

import syntax.analysis.*;

@SuppressWarnings("nls")
public final class AClosemarker extends PClosemarker
{
    private TBiginClosetag _biginClosetag_;
    private TClosetagname _closetagname_;
    private TEndClosetag _endClosetag_;

    public AClosemarker()
    {
        // Constructor
    }

    public AClosemarker(
        @SuppressWarnings("hiding") TBiginClosetag _biginClosetag_,
        @SuppressWarnings("hiding") TClosetagname _closetagname_,
        @SuppressWarnings("hiding") TEndClosetag _endClosetag_)
    {
        // Constructor
        setBiginClosetag(_biginClosetag_);

        setClosetagname(_closetagname_);

        setEndClosetag(_endClosetag_);

    }

    @Override
    public Object clone()
    {
        return new AClosemarker(
            cloneNode(this._biginClosetag_),
            cloneNode(this._closetagname_),
            cloneNode(this._endClosetag_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAClosemarker(this);
    }

    public TBiginClosetag getBiginClosetag()
    {
        return this._biginClosetag_;
    }

    public void setBiginClosetag(TBiginClosetag node)
    {
        if(this._biginClosetag_ != null)
        {
            this._biginClosetag_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._biginClosetag_ = node;
    }

    public TClosetagname getClosetagname()
    {
        return this._closetagname_;
    }

    public void setClosetagname(TClosetagname node)
    {
        if(this._closetagname_ != null)
        {
            this._closetagname_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._closetagname_ = node;
    }

    public TEndClosetag getEndClosetag()
    {
        return this._endClosetag_;
    }

    public void setEndClosetag(TEndClosetag node)
    {
        if(this._endClosetag_ != null)
        {
            this._endClosetag_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._endClosetag_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._biginClosetag_)
            + toString(this._closetagname_)
            + toString(this._endClosetag_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._biginClosetag_ == child)
        {
            this._biginClosetag_ = null;
            return;
        }

        if(this._closetagname_ == child)
        {
            this._closetagname_ = null;
            return;
        }

        if(this._endClosetag_ == child)
        {
            this._endClosetag_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._biginClosetag_ == oldChild)
        {
            setBiginClosetag((TBiginClosetag) newChild);
            return;
        }

        if(this._closetagname_ == oldChild)
        {
            setClosetagname((TClosetagname) newChild);
            return;
        }

        if(this._endClosetag_ == oldChild)
        {
            setEndClosetag((TEndClosetag) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
