/* This file was generated by SableCC (http://www.sablecc.org/). */

package syntax.node;

import syntax.analysis.*;

@SuppressWarnings("nls")
public final class AHtmldocument extends PHtmldocument
{
    private PTags _tags_;

    public AHtmldocument()
    {
        // Constructor
    }

    public AHtmldocument(
        @SuppressWarnings("hiding") PTags _tags_)
    {
        // Constructor
        setTags(_tags_);

    }

    @Override
    public Object clone()
    {
        return new AHtmldocument(
            cloneNode(this._tags_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAHtmldocument(this);
    }

    public PTags getTags()
    {
        return this._tags_;
    }

    public void setTags(PTags node)
    {
        if(this._tags_ != null)
        {
            this._tags_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tags_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tags_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tags_ == child)
        {
            this._tags_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tags_ == oldChild)
        {
            setTags((PTags) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
