package core;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'antoine' at '05/04/16 2:27 PM' with Gradle 2.12
 *
 * @author antoine, @date 05/04/16 2:27 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
