/* This file was generated by SableCC (http://www.sablecc.org/). */

package css.syntax.node;

import css.syntax.analysis.*;

@SuppressWarnings("nls")
public final class TClass extends Token
{
    public TClass(String text)
    {
        setText(text);
    }

    public TClass(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TClass(getText(), getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTClass(this);
    }
}
