/* This file was generated by SableCC (http://www.sablecc.org/). */

package css.syntax.node;

import css.syntax.analysis.*;

@SuppressWarnings("nls")
public final class TSeletor extends Token
{
    public TSeletor()
    {
        super.setText(">");
    }

    public TSeletor(int line, int pos)
    {
        super.setText(">");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSeletor(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSeletor(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSeletor text.");
    }
}
