/* This file was generated by SableCC (http://www.sablecc.org/). */

package css.syntax.node;

import css.syntax.analysis.*;

@SuppressWarnings("nls")
public final class TTag extends Token
{
    public TTag(String text)
    {
        setText(text);
    }

    public TTag(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTag(getText(), getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTag(this);
    }
}
