/* This file was generated by SableCC (http://www.sablecc.org/). */

package syntax.parser;

import syntax.lexer.*;
import syntax.node.*;
import syntax.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

@SuppressWarnings("nls")
public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList<Object> nodeList;

    private final Lexer lexer;
    private final ListIterator<Object> stack = new LinkedList<Object>().listIterator();
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(@SuppressWarnings("hiding") Lexer lexer)
    {
        this.lexer = lexer;
    }

    protected void filter() throws ParserException, LexerException, IOException
    {
        // Empty body
    }

    private void push(int numstate, ArrayList<Object> listNode, boolean hidden) throws ParserException, LexerException, IOException
    {
        this.nodeList = listNode;

        if(!hidden)
        {
            filter();
        }

        if(!this.stack.hasNext())
        {
            this.stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) this.stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            // int middle = (low + high) / 2;
            int middle = (low + high) >>> 1;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private int state()
    {
        State s = (State) this.stack.previous();
        this.stack.next();
        return s.state;
    }

    private ArrayList<Object> pop()
    {
        return ((State) this.stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        this.converter.index = -1;
        token.apply(this.converter);
        return this.converter.index;
    }

    @SuppressWarnings("unchecked")
    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null, true);
        List<Node> ign = null;
        while(true)
        {
            while(index(this.lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new LinkedList<Node>();
                }

                ign.add(this.lexer.next());
            }

            if(ign != null)
            {
                this.ignoredTokens.setIn(this.lexer.peek(), ign);
                ign = null;
            }

            this.last_pos = this.lexer.peek().getPos();
            this.last_line = this.lexer.peek().getLine();
            this.last_token = this.lexer.peek();

            int index = index(this.lexer.peek());
            this.action[0] = Parser.actionTable[state()][0][1];
            this.action[1] = Parser.actionTable[state()][0][2];

            int low = 1;
            int high = Parser.actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < Parser.actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > Parser.actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    this.action[0] = Parser.actionTable[state()][middle][1];
                    this.action[1] = Parser.actionTable[state()][middle][2];
                    break;
                }
            }

            switch(this.action[0])
            {
                case SHIFT:
		    {
		        ArrayList<Object> list = new ArrayList<Object>();
		        list.add(this.lexer.next());
                        push(this.action[1], list, false);
                    }
		    break;
                case REDUCE:
                    {
                        int reduction = this.action[1];
                        if(reduction < 500) reduce_0(reduction);
                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) this.lexer.next();
                        PHtmldocument node1 = (PHtmldocument) pop().get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(this.last_token,
                        "[" + this.last_line + "," + this.last_pos + "] " +
                        Parser.errorMessages[Parser.errors[this.action[1]]]);
            }
        }
    }

    private void reduce_0(int reduction) throws IOException, LexerException, ParserException
    {
        switch(reduction)
        {
            case 0: /* reduce AHtmldocument */
            {
                ArrayList<Object> list = new0();
                push(goTo(0), list, false);
            }
            break;
            case 1: /* reduce AAsingletagtags1Tags */
            {
                ArrayList<Object> list = new1();
                push(goTo(1), list, false);
            }
            break;
            case 2: /* reduce AAsingletagtags2Tags */
            {
                ArrayList<Object> list = new2();
                push(goTo(1), list, false);
            }
            break;
            case 3: /* reduce AAtagtags1Tags */
            {
                ArrayList<Object> list = new3();
                push(goTo(1), list, false);
            }
            break;
            case 4: /* reduce AAtagtags2Tags */
            {
                ArrayList<Object> list = new4();
                push(goTo(1), list, false);
            }
            break;
            case 5: /* reduce ATextTags */
            {
                ArrayList<Object> list = new5();
                push(goTo(1), list, false);
            }
            break;
            case 6: /* reduce AAopenmarker1Openmarker */
            {
                ArrayList<Object> list = new6();
                push(goTo(2), list, false);
            }
            break;
            case 7: /* reduce AAopenmarker2Openmarker */
            {
                ArrayList<Object> list = new7();
                push(goTo(2), list, false);
            }
            break;
            case 8: /* reduce AClosemarker */
            {
                ArrayList<Object> list = new8();
                push(goTo(3), list, false);
            }
            break;
            case 9: /* reduce AAttributes */
            {
                ArrayList<Object> list = new9();
                push(goTo(4), list, false);
            }
            break;
            case 10: /* reduce AInnertext */
            {
                ArrayList<Object> list = new10();
                push(goTo(5), list, false);
            }
            break;
            case 11: /* reduce ATerminal$Attributes */
            {
                ArrayList<Object> list = new11();
                push(goTo(6), list, true);
            }
            break;
            case 12: /* reduce ANonTerminal$Attributes */
            {
                ArrayList<Object> list = new12();
                push(goTo(6), list, true);
            }
            break;
            case 13: /* reduce ATerminal$Tags */
            {
                ArrayList<Object> list = new13();
                push(goTo(7), list, true);
            }
            break;
            case 14: /* reduce ANonTerminal$Tags */
            {
                ArrayList<Object> list = new14();
                push(goTo(7), list, true);
            }
            break;
        }
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new0() /* reduce AHtmldocument */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PHtmldocument phtmldocumentNode1;
        {
            // Block
        PTags ptagsNode2;
        ptagsNode2 = (PTags)nodeArrayList1.get(0);

        phtmldocumentNode1 = new AHtmldocument(ptagsNode2);
        }
	nodeList.add(phtmldocumentNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new1() /* reduce AAsingletagtags1Tags */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTags ptagsNode1;
        {
            // Block
        TBiginTag tbigintagNode2;
        TTagname ttagnameNode3;
        LinkedList<Object> listNode4 = new LinkedList<Object>();
        TEndSinngleTag tendsinngletagNode5;
        tbigintagNode2 = (TBiginTag)nodeArrayList1.get(0);
        ttagnameNode3 = (TTagname)nodeArrayList2.get(0);
        {
            // Block
        }
        tendsinngletagNode5 = (TEndSinngleTag)nodeArrayList3.get(0);

        ptagsNode1 = new ASingletagTags(tbigintagNode2, ttagnameNode3, listNode4, tendsinngletagNode5);
        }
	nodeList.add(ptagsNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new2() /* reduce AAsingletagtags2Tags */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTags ptagsNode1;
        {
            // Block
        TBiginTag tbigintagNode2;
        TTagname ttagnameNode3;
        LinkedList<Object> listNode5 = new LinkedList<Object>();
        TEndSinngleTag tendsinngletagNode6;
        tbigintagNode2 = (TBiginTag)nodeArrayList1.get(0);
        ttagnameNode3 = (TTagname)nodeArrayList2.get(0);
        {
            // Block
        LinkedList<Object> listNode4 = new LinkedList<Object>();
        listNode4 = (LinkedList)nodeArrayList3.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }
        tendsinngletagNode6 = (TEndSinngleTag)nodeArrayList4.get(0);

        ptagsNode1 = new ASingletagTags(tbigintagNode2, ttagnameNode3, listNode5, tendsinngletagNode6);
        }
	nodeList.add(ptagsNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new3() /* reduce AAtagtags1Tags */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTags ptagsNode1;
        {
            // Block
        POpenmarker popenmarkerNode2;
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        PClosemarker pclosemarkerNode4;
        popenmarkerNode2 = (POpenmarker)nodeArrayList1.get(0);
        {
            // Block
        }
        pclosemarkerNode4 = (PClosemarker)nodeArrayList2.get(0);

        ptagsNode1 = new ATagTags(popenmarkerNode2, listNode3, pclosemarkerNode4);
        }
	nodeList.add(ptagsNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new4() /* reduce AAtagtags2Tags */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTags ptagsNode1;
        {
            // Block
        POpenmarker popenmarkerNode2;
        LinkedList<Object> listNode4 = new LinkedList<Object>();
        PClosemarker pclosemarkerNode5;
        popenmarkerNode2 = (POpenmarker)nodeArrayList1.get(0);
        {
            // Block
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        listNode3 = (LinkedList)nodeArrayList2.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }
        pclosemarkerNode5 = (PClosemarker)nodeArrayList3.get(0);

        ptagsNode1 = new ATagTags(popenmarkerNode2, listNode4, pclosemarkerNode5);
        }
	nodeList.add(ptagsNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new5() /* reduce ATextTags */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTags ptagsNode1;
        {
            // Block
        TText ttextNode2;
        ttextNode2 = (TText)nodeArrayList1.get(0);

        ptagsNode1 = new ATextTags(ttextNode2);
        }
	nodeList.add(ptagsNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new6() /* reduce AAopenmarker1Openmarker */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        POpenmarker popenmarkerNode1;
        {
            // Block
        TBiginTag tbigintagNode2;
        TTagname ttagnameNode3;
        LinkedList<Object> listNode4 = new LinkedList<Object>();
        TEndTag tendtagNode5;
        tbigintagNode2 = (TBiginTag)nodeArrayList1.get(0);
        ttagnameNode3 = (TTagname)nodeArrayList2.get(0);
        {
            // Block
        }
        tendtagNode5 = (TEndTag)nodeArrayList3.get(0);

        popenmarkerNode1 = new AOpenmarker(tbigintagNode2, ttagnameNode3, listNode4, tendtagNode5);
        }
	nodeList.add(popenmarkerNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new7() /* reduce AAopenmarker2Openmarker */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        POpenmarker popenmarkerNode1;
        {
            // Block
        TBiginTag tbigintagNode2;
        TTagname ttagnameNode3;
        LinkedList<Object> listNode5 = new LinkedList<Object>();
        TEndTag tendtagNode6;
        tbigintagNode2 = (TBiginTag)nodeArrayList1.get(0);
        ttagnameNode3 = (TTagname)nodeArrayList2.get(0);
        {
            // Block
        LinkedList<Object> listNode4 = new LinkedList<Object>();
        listNode4 = (LinkedList)nodeArrayList3.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }
        tendtagNode6 = (TEndTag)nodeArrayList4.get(0);

        popenmarkerNode1 = new AOpenmarker(tbigintagNode2, ttagnameNode3, listNode5, tendtagNode6);
        }
	nodeList.add(popenmarkerNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new8() /* reduce AClosemarker */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PClosemarker pclosemarkerNode1;
        {
            // Block
        TBiginClosetag tbiginclosetagNode2;
        TClosetagname tclosetagnameNode3;
        TEndClosetag tendclosetagNode4;
        tbiginclosetagNode2 = (TBiginClosetag)nodeArrayList1.get(0);
        tclosetagnameNode3 = (TClosetagname)nodeArrayList2.get(0);
        tendclosetagNode4 = (TEndClosetag)nodeArrayList3.get(0);

        pclosemarkerNode1 = new AClosemarker(tbiginclosetagNode2, tclosetagnameNode3, tendclosetagNode4);
        }
	nodeList.add(pclosemarkerNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new9() /* reduce AAttributes */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PAttributes pattributesNode1;
        {
            // Block
        TAttrKey tattrkeyNode2;
        TAttrValue tattrvalueNode3;
        tattrkeyNode2 = (TAttrKey)nodeArrayList1.get(0);
        tattrvalueNode3 = (TAttrValue)nodeArrayList2.get(0);

        pattributesNode1 = new AAttributes(tattrkeyNode2, tattrvalueNode3);
        }
	nodeList.add(pattributesNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new10() /* reduce AInnertext */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PInnertext pinnertextNode1;
        {
            // Block
        TText ttextNode2;
        ttextNode2 = (TText)nodeArrayList1.get(0);

        pinnertextNode1 = new AInnertext(ttextNode2);
        }
	nodeList.add(pinnertextNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new11() /* reduce ATerminal$Attributes */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        {
            // Block
        PAttributes pattributesNode1;
        pattributesNode1 = (PAttributes)nodeArrayList1.get(0);
	if(pattributesNode1 != null)
	{
	  listNode2.add(pattributesNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new12() /* reduce ANonTerminal$Attributes */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode1 = new LinkedList<Object>();
        PAttributes pattributesNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pattributesNode2 = (PAttributes)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pattributesNode2 != null)
	{
	  listNode3.add(pattributesNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new13() /* reduce ATerminal$Tags */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        {
            // Block
        PTags ptagsNode1;
        ptagsNode1 = (PTags)nodeArrayList1.get(0);
	if(ptagsNode1 != null)
	{
	  listNode2.add(ptagsNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new14() /* reduce ANonTerminal$Tags */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode1 = new LinkedList<Object>();
        PTags ptagsNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        ptagsNode2 = (PTags)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(ptagsNode2 != null)
	{
	  listNode3.add(ptagsNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, ERROR, 0}, {0, SHIFT, 1}, {1, SHIFT, 2}, },
			{{-1, REDUCE, 5}, },
			{{-1, ERROR, 2}, {2, SHIFT, 6}, },
			{{-1, ERROR, 3}, {10, ACCEPT, -1}, },
			{{-1, REDUCE, 0}, },
			{{-1, ERROR, 5}, {0, SHIFT, 1}, {1, SHIFT, 2}, {7, SHIFT, 7}, },
			{{-1, ERROR, 6}, {3, SHIFT, 11}, {5, SHIFT, 12}, {6, SHIFT, 13}, },
			{{-1, ERROR, 7}, {8, SHIFT, 16}, },
			{{-1, REDUCE, 13}, },
			{{-1, REDUCE, 3}, },
			{{-1, ERROR, 10}, {0, SHIFT, 1}, {1, SHIFT, 2}, {7, SHIFT, 7}, },
			{{-1, ERROR, 11}, {4, SHIFT, 19}, },
			{{-1, REDUCE, 1}, },
			{{-1, REDUCE, 6}, },
			{{-1, REDUCE, 11}, },
			{{-1, ERROR, 15}, {3, SHIFT, 11}, {5, SHIFT, 20}, {6, SHIFT, 21}, },
			{{-1, ERROR, 16}, {9, SHIFT, 23}, },
			{{-1, REDUCE, 14}, },
			{{-1, REDUCE, 4}, },
			{{-1, REDUCE, 9}, },
			{{-1, REDUCE, 2}, },
			{{-1, REDUCE, 7}, },
			{{-1, REDUCE, 12}, },
			{{-1, REDUCE, 8}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 3}, },
			{{-1, 4}, {5, 8}, {10, 17}, },
			{{-1, 5}, },
			{{-1, 9}, {10, 18}, },
			{{-1, 14}, {15, 22}, },
			{{-1, -1}, },
			{{-1, 15}, },
			{{-1, 10}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: text, '<'",
			"expecting: text, '<', bigin closetag, EOF",
			"expecting: tagname",
			"expecting: EOF",
			"expecting: text, '<', bigin closetag",
			"expecting: attr key, '/>', '>'",
			"expecting: closetagname",
			"expecting: attr value",
			"expecting: end closetag",
        };*/
    private static int[] errors;
/*      {
			0, 1, 2, 3, 3, 4, 5, 6, 4, 1, 4, 7, 1, 4, 5, 5, 8, 4, 1, 5, 1, 4, 5, 1, 
        };*/

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Parser.class.getResourceAsStream("parser.dat")));

            // read actionTable
            int length = s.readInt();
            Parser.actionTable = new int[length][][];
            for(int i = 0; i < Parser.actionTable.length; i++)
            {
                length = s.readInt();
                Parser.actionTable[i] = new int[length][3];
                for(int j = 0; j < Parser.actionTable[i].length; j++)
                {
                for(int k = 0; k < 3; k++)
                {
                    Parser.actionTable[i][j][k] = s.readInt();
                }
                }
            }

            // read gotoTable
            length = s.readInt();
            gotoTable = new int[length][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][2];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                for(int k = 0; k < 2; k++)
                {
                    gotoTable[i][j][k] = s.readInt();
                }
                }
            }

            // read errorMessages
            length = s.readInt();
            errorMessages = new String[length];
            for(int i = 0; i < errorMessages.length; i++)
            {
                length = s.readInt();
                StringBuffer buffer = new StringBuffer();

                for(int j = 0; j < length; j++)
                {
                buffer.append(s.readChar());
                }
                errorMessages[i] = buffer.toString();
            }

            // read errors
            length = s.readInt();
            errors = new int[length];
            for(int i = 0; i < errors.length; i++)
            {
                errors[i] = s.readInt();
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
        }
    }
}
