/* This file was generated by SableCC (http://www.sablecc.org/). */

package syntax.parser;

import syntax.node.*;
import syntax.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTText(@SuppressWarnings("unused") TText node)
    {
        this.index = 0;
    }

    @Override
    public void caseTBiginTag(@SuppressWarnings("unused") TBiginTag node)
    {
        this.index = 1;
    }

    @Override
    public void caseTTagname(@SuppressWarnings("unused") TTagname node)
    {
        this.index = 2;
    }

    @Override
    public void caseTAttrKey(@SuppressWarnings("unused") TAttrKey node)
    {
        this.index = 3;
    }

    @Override
    public void caseTAttrValue(@SuppressWarnings("unused") TAttrValue node)
    {
        this.index = 4;
    }

    @Override
    public void caseTEndSinngleTag(@SuppressWarnings("unused") TEndSinngleTag node)
    {
        this.index = 5;
    }

    @Override
    public void caseTEndTag(@SuppressWarnings("unused") TEndTag node)
    {
        this.index = 6;
    }

    @Override
    public void caseTBiginClosetag(@SuppressWarnings("unused") TBiginClosetag node)
    {
        this.index = 7;
    }

    @Override
    public void caseTClosetagname(@SuppressWarnings("unused") TClosetagname node)
    {
        this.index = 8;
    }

    @Override
    public void caseTEndClosetag(@SuppressWarnings("unused") TEndClosetag node)
    {
        this.index = 9;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 10;
    }
}
