import org.junit.Test;
import static org.junit.Assert.*;

import core.Library;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'antoine' at '05/04/16 2:27 PM' with Gradle 2.12
 *
 * @author antoine, @date 05/04/16 2:27 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
