/* This file was generated by SableCC (http://www.sablecc.org/). */

package css.syntax.analysis;

import css.syntax.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTId(TId node);
    void caseTClass(TClass node);
    void caseTTag(TTag node);
    void caseTSeletor(TSeletor node);
    void caseTBlank(TBlank node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
